# Generated by Django 4.2.1 on 2023-06-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodreviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.CharField(max_length=220)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('hotel_location', models.CharField(max_length=220)),
                ('hotel_name', models.CharField(max_length=220)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('Items_review', models.CharField(max_length=520)),
                ('Items_ratings', models.IntegerField()),
                ('hotel_review', models.CharField(max_length=520)),
                ('hotel_ratings', models.IntegerField()),
            ],
        ),
    ]
