# Generated by Django 4.2.1 on 2023-07-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Foodreviewapp', '0007_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
