# Generated by Django 4.2.1 on 2023-07-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodreviewapp', '0009_hotel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_hotel', models.CharField(max_length=220)),
                ('hotel_location', models.CharField(max_length=220)),
                ('hotel_name', models.CharField(max_length=220)),
                ('hotel_email', models.EmailField(max_length=254)),
                ('hotel_ratings', models.IntegerField()),
                ('thumbnail_pic', models.CharField(max_length=220)),
            ],
        ),
    ]
